export const QUERIES = {
  GENRES_LIST: 'GENRES_LIST' as const,
  SECTIONS_LIST: 'SECTIONS_LIST' as const,
  MOVIES_LIST: 'MOVIES_LIST' as const,
  MOVIE_DETAIL_LIST: 'MOVIE_DETAIL_LIST' as const,
};
