version: '3.7'
services:
  web-app-service:
    build: .
    image: web-app:1.0
    container_name: web-app
    ports:
      - "8800:80"
    restart: always
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.web-app.entrypoints=websecure"
      - "traefik.http.routers.web-app.rule=Host(`app-dev.vietmyipc.com`)"
networks:
  proxy:
    external: true
