version: '3.7'

services:
  app:
    image: amonish/amonish:v1
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: /app/entrypoint.sh
    environment:
      NODE_ENV: development
